version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    networks:
      - private
  app:
    build: ./
    ports:
      - "8000:80"
    volumes:
      - ./:/app
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
    depends_on:
      - db
    networks:
      - private
      - public

networks:
  public:
  private:
   internal: true
